### ISSUE TITLE
Set up Next-Auth (Azure AD Provider)

### ISSUE THREAD

**Issue by Djontleman** [DanaMurali/The_Chiron_Project#30]
### Tasks

- [x] Add Web application with `localhost` re-direct URL (includes access tokens)
- [x] Add environment variables
- [x] Do a successful login
