### ISSUE TITLE
Set up Prisma

### ISSUE THREAD

**Issue by Djontleman** [DanaMurali/The_Chiron_Project#35]
### Tasks

- [x] Use MySQL as Prisma provider
- [x] Make database migration
- [x] Use Prisma Studio

### Supporting documentation

Prisma docs: https://www.prisma.io/docs/getting-started

**Comment by Djontleman** [comment]
Prisma commands:
- `prisma generate` to (re-)generate Prisma Client whenever the Prisma schema is modified, to update the generated code
- `prisma migrate dev` to generate database migrations in development
- `prisma db push` for prototyping and `prisma migrate reset` to undo changes
- `prisma migrate deploy` to apply migrations in production and  testing
- `prisma studio` to start Prisma Studio for interacting with database
