### ISSUE TITLE
Deploy to Vercel

### ISSUE THREAD

**Issue by Djontleman** [DanaMurali/The_Chiron_Project#48]
### Tasks

- [ ] Create Vercel account
- [ ] Link project to Vercel
- [ ] Add deployment workflow(s) to GitHub Actions
- [ ] Deploy to Vercel

### Supporting Documentation

https://vercel.com/guides/how-can-i-use-github-actions-with-vercel
